main: com.minegusta.commandgui.Main
name: CommandGui
version: ${project.version}
author: janie177

commands:
   gui:
      description: The Command Help Menu.
      usage: /GUI
      aliases: [command, ui, interface, openmenu, teleports, servers, menu, mg, commands, cmd, cmds]